version: '4.28'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: rokoperisic
      POSTGRES_PASSWORD: 100441
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

  